# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tuxtaperui.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormMain(object):
    def setupUi(self, FormMain):
        FormMain.setObjectName("FormMain")
        FormMain.resize(617, 490)
        FormMain.setAutoFillBackground(False)
        self.pushButtonPause = QtWidgets.QPushButton(FormMain)
        self.pushButtonPause.setGeometry(QtCore.QRect(520, 390, 80, 80))
        self.pushButtonPause.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonPause.setCheckable(True)
        self.pushButtonPause.setObjectName("pushButtonPause")
        self.pushButtonStop = QtWidgets.QPushButton(FormMain)
        self.pushButtonStop.setGeometry(QtCore.QRect(420, 390, 80, 80))
        self.pushButtonStop.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonStop.setCheckable(True)
        self.pushButtonStop.setObjectName("pushButtonStop")
        self.pushButtonAdvance = QtWidgets.QPushButton(FormMain)
        self.pushButtonAdvance.setGeometry(QtCore.QRect(320, 390, 80, 80))
        self.pushButtonAdvance.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonAdvance.setCheckable(True)
        self.pushButtonAdvance.setObjectName("pushButtonAdvance")
        self.pushButtonRewind = QtWidgets.QPushButton(FormMain)
        self.pushButtonRewind.setEnabled(True)
        self.pushButtonRewind.setGeometry(QtCore.QRect(220, 390, 80, 80))
        self.pushButtonRewind.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonRewind.setCheckable(True)
        self.pushButtonRewind.setObjectName("pushButtonRewind")
        self.pushButtonPlay = QtWidgets.QPushButton(FormMain)
        self.pushButtonPlay.setGeometry(QtCore.QRect(120, 390, 80, 80))
        self.pushButtonPlay.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonPlay.setAutoFillBackground(True)
        self.pushButtonPlay.setStyleSheet("color: green;\n"
"selection-background-color: rgb(16, 255, 16);")
        self.pushButtonPlay.setObjectName("pushButtonPlay")
        self.pushButtonRecord = QtWidgets.QPushButton(FormMain)
        self.pushButtonRecord.setGeometry(QtCore.QRect(20, 390, 80, 80))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 128, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(233, 115, 113))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(202, 100, 99))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 80, 81))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 128, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(233, 115, 113))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(202, 100, 99))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 80, 81))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 128, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(233, 115, 113))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(202, 100, 99))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 80, 81))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.pushButtonRecord.setPalette(palette)
        self.pushButtonRecord.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonRecord.setAutoFillBackground(False)
        self.pushButtonRecord.setStyleSheet("color: red;")
        self.pushButtonRecord.setCheckable(True)
        self.pushButtonRecord.setObjectName("pushButtonRecord")
        self.labelTape = QtWidgets.QLabel(FormMain)
        self.labelTape.setGeometry(QtCore.QRect(30, 90, 391, 251))
        self.labelTape.setText("")
        self.labelTape.setPixmap(QtGui.QPixmap(":/images/graphics/cassetteempty.jpg"))
        self.labelTape.setObjectName("labelTape")
        self.labelFilename = QtWidgets.QLabel(FormMain)
        self.labelFilename.setGeometry(QtCore.QRect(60, 50, 321, 41))
        self.labelFilename.setText("")
        self.labelFilename.setObjectName("labelFilename")

        self.retranslateUi(FormMain)
        QtCore.QMetaObject.connectSlotsByName(FormMain)

    def retranslateUi(self, FormMain):
        _translate = QtCore.QCoreApplication.translate
        FormMain.setWindowTitle(_translate("FormMain", "Tux Taper"))
        self.pushButtonPause.setText(_translate("FormMain", "Pause"))
        self.pushButtonStop.setText(_translate("FormMain", "Stop"))
        self.pushButtonAdvance.setText(_translate("FormMain", "Advance"))
        self.pushButtonRewind.setText(_translate("FormMain", "Rewind"))
        self.pushButtonPlay.setText(_translate("FormMain", "Play"))
        self.pushButtonRecord.setText(_translate("FormMain", "Record"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FormMain = QtWidgets.QWidget()
    ui = Ui_FormMain()
    ui.setupUi(FormMain)
    FormMain.show()
    sys.exit(app.exec_())
